
services:
  frontend:
    image: python:3.12
    volumes:
      - ./frontend:/app
    working_dir: /app
    environment:
      - API_BASE_URL=${API_BASE_URL}
    command: >
      sh -c "apt-get update && apt-get upgrade -y && pip install --upgrade pip && pip install  --no-cache-dir -r requirements.txt && streamlit run app.py --server.port=8501 --server.address=0.0.0.0"
    ports:
      - "8501:8501"
    depends_on:
      - db
      - api
  
  api:
    image: watchdogweb-api:latest 
    build: ./api
    volumes:
      - ./api:/app
    working_dir: /app
    environment:
    - SECRET_KEY=${SECRET_KEY}
    - DB_HOST=${DB_HOST}
    - DB_PORT=${DB_PORT}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_NAME=${DB_NAME}
    - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
    - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
    - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
    - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
    - MICROSOFT_REDIRECT_URI=${MICROSOFT_REDIRECT_URI}
    - X_CLIENT_ID=${X_CLIENT_ID}
    - X_CLIENT_SECRET=${X_CLIENT_SECRET}
    - X_REDIRECT_URI=${X_REDIRECT_URI}
    command: >
      bash -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 80"
    ports:
      - "8000:80"
    depends_on:
      - db

  sensor_simulator:
    image: python:3.12
    volumes:
      - ./simulator:/app
    working_dir: /app
    command: >
      bash -c "apt-get update && apt-get upgrade -y && pip install -r requirements.txt && python sim.py"
    depends_on:
      - api

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - /postgres_data:/var/lib/postgresql/data
      - ./postgres_backups:/backups

volumes:
  postgres_data:
