
services:
  frontend:
    image: python:3.12
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: >
      sh -c "apt-get update && apt-get upgrade -y && pip install --upgrade pip && pip install  --no-cache-dir -r requirements.txt && streamlit run app.py --server.port=8501 --server.address=0.0.0.0"
    ports:
      - "8501:8501"
    depends_on:
      - db
      - api
  
  api:
    image: watchdogweb-api:latest 
    build: ./api
    volumes:
      - ./api:/app
    working_dir: /app
    command: >
      bash -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 80"
    ports:
      - "8000:80"
    depends_on:
      - db

  sensor_simulator:
    image: python:3.12
    volumes:
      - ./simulator:/app
    working_dir: /app
    command: >
      bash -c "apt-get update && apt-get upgrade -y && pip install -r requirements.txt && python sim.py"
    depends_on:
      - api

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/backups
